name: Container Deploy

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    env:
      REGISTRY: ghcr.io
      IMAGE_NAME: ${{ github.repository }}
      VERCEL_DEPLOY_HOOK_URL: ${{ secrets.VERCEL_DEPLOY_HOOK_URL }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=sha
            type=ref,event=branch
            type=raw,value=latest,enable=${{ github.ref == 'refs/heads/main' }}

      - name: Build and push image
        id: build
        uses: docker/build-push-action@v6
        with:
          context: .
          file: Dockerfile
          platforms: linux/amd64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            DATABASE_URL=postgresql://placeholder:placeholder@localhost:5432/placeholder

      - name: Trigger Vercel deploy hook
        if: ${{ env.VERCEL_DEPLOY_HOOK_URL != '' }}
        env:
          DEPLOY_HOOK: ${{ env.VERCEL_DEPLOY_HOOK_URL }}
        run: |
          http_code=$(curl -s -o /tmp/vercel-response.txt -w "%{http_code}" -X POST "$DEPLOY_HOOK")
          cat /tmp/vercel-response.txt
          if [ "$http_code" -ge 400 ]; then
            echo "Vercel deploy hook returned status $http_code" >&2
            exit 1
          fi
          echo "Vercel deploy hook accepted with status $http_code"
